import { FaCalendarAlt } from 'react-icons/fa';
import { FaClock } from 'react-icons/fa';
import image from '../assets/images/image.png'
import image3 from '../assets/images/image3.png'
import image4 from '../assets/images/image4.png'
import image5 from '../assets/images/image5.png'
import image6 from '../assets/images/image6.png'
import image8 from '../assets/images/image8.png'
import image9 from '../assets/images/image9.png'
import image10 from '../assets/images/image10.png'
import image11 from '../assets/images/image11.png'
import image12 from '../assets/images/image12.png'
import image13 from '../assets/images/image13.png'
import image14 from '../assets/images/image14.png'
import image16 from '../assets/images/image16.png'
import image17 from '../assets/images/image17.png'
import image18 from '../assets/images/image18.png'
import imageCourse1 from '../assets/images/image-1.png'
import imageCourse2 from '../assets/images/image-2.png'
import imageCourse3 from '../assets/images/image-3.png'
import { MdInsights, MdOutlinePerson3, MdSettings } from "react-icons/md";
import { LiaDiscourse } from "react-icons/lia";
import LoadingIcon from '../assets/images/icon/LoadingIcon'

export const links = [
  { _id: "1", name: "Blog", link: "/blog" },
  { _id: "2", name: "Who We Are", link: "/whoWeAre", },
  { _id: "3", name: "What We Do", link: "/whatWeDo", },
  { _id: "4", name: "Courses", link: "/course", },
  { _id: "5", name: "Contact Us", link: "/contactus" },
];

export const companyLinks = [
  { link: '/aboutus', name: 'About Us' },
  { link: '/value', name: 'Values' },
  { link: '/consulting', name: 'Consulting' },
  { link: '/course', name: 'Courses' },
];

export const resourcesLinks = [
  { link: '/blog', name: 'Blog' },
  { link: '/forums', name: 'Form' },
  { link: '/contactus', name: 'Contact Us' },
  { link: '/faq', name: 'FAQs' },
];

export const legalLinks = [
  { link: '/privacy', name: 'Privacy Policy' },
  { link: '/terms', name: 'Terms of Service' },
  { link: '/policy', name: 'AI Policy' },
];

export const blogs = [
  {
    _id: "1",
    image: image6,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Data Science",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "2",
    image: image6,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "SQL",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "3",
    image: image6,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Python",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "4",
    image: image6,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Data Science",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "5",
    image: image9,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "SQL",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "6",
    image: image10,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Python",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "7",
    image: image11,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Data Science",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "8",
    image: image12,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Data Science",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "9",
    image: image13,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "SQL",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "10",
    image: image14,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Python",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "11",
    image: image9,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Data Science",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "12",
    image: image10,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "SQL",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "13",
    image: image10,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Python",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "14",
    image: image10,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Python",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "15",
    image: image10,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "SQL",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
  {
    _id: "16",
    image: image14,
    title: "What we are capable to usually discovered",
    name: "John Doe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit....",
    date: "11 Jan 2022",
    time: "5 min read",
    category: "Data Science",
    avatar: image8,
    Icon: FaCalendarAlt,
    school: "Technische Universität Berlin",
  },
];

export const slides = [
  {
    _id: "1",
    title: "data analytics",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
  },
  {
    _id: "2",
    title: "Policy Analysis and Research",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
  },
  {
    _id: "3",
    title: "Training",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
  },
];

export const courses = [
  {
    _id: "1",
    image: image3,
    category: "business analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "11h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "2",
    image: image4,
    category: "financial analysis",
     title: "Financial Analyst Training & Investing Course",
     text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
     name: "Robert Fox",
     avatar: image8,
     time: "11h 20m",
     price: "15.00",
     Icon: FaClock,
  },
  {
    _id: "3",
    image: image5,
    category: "web analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "11h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "4",
    image: imageCourse1,
    category: "data analysis",
    title: "Medium length section heading goes here",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    name: "Robert Fox",
    avatar: image8,
    time: "11h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "5",
    image: image5,
    category: "web analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "11h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "6",
    image: imageCourse2,
    category: "mathematical analysis",
    title: "Medium length section heading goes here",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    name: "Robert Fox",
    avatar: image8,
    time: "11h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "7",
    image: image4,
    category: "financial analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "4h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "8",
    image: image5,
    category: "web analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "11h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "9",
    image: imageCourse1,
    category: "data analysis",
    title: "Medium length section heading goes here",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    name: "Robert Fox",
    avatar: image8,
    time: "8h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "10",
    image: image3,
    category: "business analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "1h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "11",
    image: image5,
    category: "web analysis",
    title: "Medium length section heading goes here",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    name: "Robert Fox",
    avatar: image8,
    time: "6h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "12",
    image: image4,
    category: "financial analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "1h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "13",
    image: imageCourse2,
    category: "mathematical analysis",
    title: "Medium length section heading goes here",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    name: "Robert Fox",
    avatar: image8,
    time: "11h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "14",
    image: imageCourse3,
    category: "marketing analysis",
    title: "Medium length section heading goes here",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    name: "Robert Fox",
    avatar: image8,
    time: "5h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "15",
    image: image5,
    category: "web analysis",
    title: "Financial Analyst Training & Investing Course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    name: "Robert Fox",
    avatar: image8,
    time: "1h 20m",
    price: "15.00",
    Icon: FaClock,
  },
  {
    _id: "16",
    image: imageCourse3,
    category: "marketing analysis",
    title: "Medium length section heading goes here",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    name: "Robert Fox",
    avatar: image8,
    time: "3h 20m",
    price: "15.00",
    Icon: FaClock,
  },
];

export const tables = [
  {
    _id: "1",
    title: "1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    text: "This discussion forum is designed to provide an avenue for connecting with other members from across the world. The general discussion forum is meant for general discussions so feel free to post whether the topic is data, public policy or anything else you think other members might find interesting.",
    topics: "1",
    post: "14",
    lastPost: "No Topics",
  },
  {
    _id: "2",
    title: "2. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    text: "This discussion forum is designed to provide an avenue for connecting with other members from across the world. The general discussion forum is meant for general discussions so feel free to post whether the topic is data, public policy or anything else you think other members might find interesting.",
    topics: "2",
    post: "14",
    lastPost: "14",
  },
  {
    _id: "3",
    title: "3. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    text: "This discussion forum is designed to provide an avenue for connecting with other members from across the world. The general discussion forum is meant for general discussions so feel free to post whether the topic is data, public policy or anything else you think other members might find interesting.",
    topics: "5",
    post: "14",
    lastPost: "14",
  },
  {
    _id: "4",
    title: "4. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    text: "This discussion forum is designed to provide an avenue for connecting with other members from across the world. The general discussion forum is meant for general discussions so feel free to post whether the topic is data, public policy or anything else you think other members might find interesting.",
    topics: "2",
    post: "14",
    lastPost: "14",
  },
  {
    _id: "5",
    title: "5. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    text: "This discussion forum is designed to provide an avenue for connecting with other members from across the world. The general discussion forum is meant for general discussions so feel free to post whether the topic is data, public policy or anything else you think other members might find interesting.",
    topics: "1",
    post: "14",
    lastPost: "14",
  },
];

export const items = [
  {
    _id: "1",
    title: "Insights",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    Icon: MdInsights,
  },
  {
    _id: "2",
    title: "Courses",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    Icon: LiaDiscourse,
  },
  {
    _id: "3",
    title: "Consulting",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    Icon: MdOutlinePerson3,
  },
];

export const values = [
  {
    _id: "1",
    value: "1",
    name: "Custom analytics",
    text: "Get a complete sales dashboard in the cloud. See activity, revenue and social metrics all in one place.",
  },
  {
    _id: "2",
    value: "2",
    name: "Team Management",
    text: "Our calendar lets you know what is happening with customer and projects so you are able to control process.",
  },
  {
    _id: "3",
    value: "3",
    name: "Easy setup",
    text: "End to End Business Platform, Sales Management, Marketing Automation, Help Desk and many more",
  },
  {
    _id: "4",
    value: "4",
    name: "Build your website",
    text: "A tool that lets you build a dream website even if you know nothing about web design or programming.",
  },
];

export const services = [
  {
    _id: "1",
    image: image,
    name: "Policy Analysis",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
  },
  {
    _id: "2",
    image: image16,
    name: "Research",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
  },
  {
    _id: "3",
    image: image17,
    name: "Bespoke Training",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
  },
  {
    _id: "4",
    image: image18,
    name: "Data Analytics and Modelling",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
  },
];

export const learns = [
  {
    _id: "1",
    title: "Medium length heading goes here",
    text: "Get a complete sales dashboard in the cloud. See activity, revenue and social metrics all in one place.",
    Icon: MdInsights,
  },
  {
    _id: "2",
    title: "Medium length heading goes here",
    text: "Our calendar lets you know what is happening with customer and projects so you",
    Icon: MdOutlinePerson3,
  },
  {
    _id: "3",
    title: "Medium length heading goes here",
    text: "The first business platform to bring together all of your products from one place.",
    Icon: LiaDiscourse,
  },
  {
    _id: "4",
    title: "Medium length heading goes here",
    text: "End to End Business Platform, Sales Management, Marketing Automation, Help Desk",
    Icon: MdSettings,
  },
];

export const reviews = [
  {
    _id: "1",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
    avatar: image8,
    name: "john don",
    position: "CEO",
    company: "Company name",
  },
  {
    _id: "2",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
    avatar: image8,
    name: "john don",
    position: "manager",
    company: "Company name",
  },
  {
    _id: "3",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
    avatar: image8,
    name: "john don",
    position: "CEO",
    company: "Company name",
  },
  {
    _id: "4",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
    avatar: image8,
    name: "john don",
    position: "manager",
    company: "Company name",
  },
  {
    _id: "5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
    avatar: image8,
    name: "john don",
    position: "technology",
    company: "Company name",
  },
];

export const vidoes = [
  {
    _id: "1",
    value: "1",
    name: "Navigating the course",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    time: "6min",
    Icon: LoadingIcon,
  },
  {
    _id: "2",
    value: "4",
    name: "Tips for learning R",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    time: "3min",
    Icon: LoadingIcon,
  },
  {
    _id: "3",
    value: "2",
    name: "Useful resources",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    time: "5min",
    Icon: LoadingIcon,
  },
  {
    _id: "4",
    value: "3",
    name: "Setting up R and R studio",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.",
    time: "8min",
    Icon: LoadingIcon,
  },
];

export const resources = [
  {
    _id: "1",
    value: "2",
    name: "Lorem ipsum Docxx."
  },
  {
    _id: "2",
    value: "5",
    name: "Lorem ipsum Docxx."
  },
  {
    _id: "3",
    value: "3",
    name: "Lorem ipsum Docxx."
  },
  {
    _id: "4",
    value: "6",
    name: "Lorem ipsum Docxx."
  },
];
